// ============================================
//  LINGUAFLOW — LANGUAGES DATABASE
// ============================================

const LANGUAGES = [
  { code: 'af',    name: 'Afrikaans',   flag: '🇿🇦' },
  { code: 'sq',    name: 'Albanian',    flag: '🇦🇱' },
  { code: 'ar',    name: 'Arabic',      flag: '🇸🇦' },
  { code: 'hy',    name: 'Armenian',    flag: '🇦🇲' },
  { code: 'az',    name: 'Azerbaijani', flag: '🇦🇿' },
  { code: 'eu',    name: 'Basque',      flag: '🏴' },
  { code: 'be',    name: 'Belarusian',  flag: '🇧🇾' },
  { code: 'bn',    name: 'Bengali',     flag: '🇧🇩' },
  { code: 'bs',    name: 'Bosnian',     flag: '🇧🇦' },
  { code: 'bg',    name: 'Bulgarian',   flag: '🇧🇬' },
  { code: 'ca',    name: 'Catalan',     flag: '🏴' },
  { code: 'zh',    name: 'Chinese (Simplified)',  flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', flag: '🇹🇼' },
  { code: 'hr',    name: 'Croatian',    flag: '🇭🇷' },
  { code: 'cs',    name: 'Czech',       flag: '🇨🇿' },
  { code: 'da',    name: 'Danish',      flag: '🇩🇰' },
  { code: 'nl',    name: 'Dutch',       flag: '🇳🇱' },
  { code: 'en',    name: 'English',     flag: '🇬🇧' },
  { code: 'eo',    name: 'Esperanto',   flag: '🟢' },
  { code: 'et',    name: 'Estonian',    flag: '🇪🇪' },
  { code: 'fi',    name: 'Finnish',     flag: '🇫🇮' },
  { code: 'fr',    name: 'French',      flag: '🇫🇷' },
  { code: 'gl',    name: 'Galician',    flag: '🏴' },
  { code: 'ka',    name: 'Georgian',    flag: '🇬🇪' },
  { code: 'de',    name: 'German',      flag: '🇩🇪' },
  { code: 'el',    name: 'Greek',       flag: '🇬🇷' },
  { code: 'gu',    name: 'Gujarati',    flag: '🇮🇳' },
  { code: 'ht',    name: 'Haitian Creole', flag: '🇭🇹' },
  { code: 'he',    name: 'Hebrew',      flag: '🇮🇱' },
  { code: 'hi',    name: 'Hindi',       flag: '🇮🇳' },
  { code: 'hu',    name: 'Hungarian',   flag: '🇭🇺' },
  { code: 'is',    name: 'Icelandic',   flag: '🇮🇸' },
  { code: 'id',    name: 'Indonesian',  flag: '🇮🇩' },
  { code: 'ga',    name: 'Irish',       flag: '🇮🇪' },
  { code: 'it',    name: 'Italian',     flag: '🇮🇹' },
  { code: 'ja',    name: 'Japanese',    flag: '🇯🇵' },
  { code: 'jv',    name: 'Javanese',    flag: '🇮🇩' },
  { code: 'kn',    name: 'Kannada',     flag: '🇮🇳' },
  { code: 'kk',    name: 'Kazakh',      flag: '🇰🇿' },
  { code: 'ko',    name: 'Korean',      flag: '🇰🇷' },
  { code: 'la',    name: 'Latin',       flag: '🏛️' },
  { code: 'lv',    name: 'Latvian',     flag: '🇱🇻' },
  { code: 'lt',    name: 'Lithuanian',  flag: '🇱🇹' },
  { code: 'mk',    name: 'Macedonian',  flag: '🇲🇰' },
  { code: 'ms',    name: 'Malay',       flag: '🇲🇾' },
  { code: 'ml',    name: 'Malayalam',   flag: '🇮🇳' },
  { code: 'mt',    name: 'Maltese',     flag: '🇲🇹' },
  { code: 'mr',    name: 'Marathi',     flag: '🇮🇳' },
  { code: 'mn',    name: 'Mongolian',   flag: '🇲🇳' },
  { code: 'ne',    name: 'Nepali',      flag: '🇳🇵' },
  { code: 'no',    name: 'Norwegian',   flag: '🇳🇴' },
  { code: 'fa',    name: 'Persian',     flag: '🇮🇷' },
  { code: 'pl',    name: 'Polish',      flag: '🇵🇱' },
  { code: 'pt',    name: 'Portuguese',  flag: '🇵🇹' },
  { code: 'pa',    name: 'Punjabi',     flag: '🇵🇰' },
  { code: 'ro',    name: 'Romanian',    flag: '🇷🇴' },
  { code: 'ru',    name: 'Russian',     flag: '🇷🇺' },
  { code: 'sr',    name: 'Serbian',     flag: '🇷🇸' },
  { code: 'sk',    name: 'Slovak',      flag: '🇸🇰' },
  { code: 'sl',    name: 'Slovenian',   flag: '🇸🇮' },
  { code: 'es',    name: 'Spanish',     flag: '🇪🇸' },
  { code: 'sw',    name: 'Swahili',     flag: '🇰🇪' },
  { code: 'sv',    name: 'Swedish',     flag: '🇸🇪' },
  { code: 'tl',    name: 'Tagalog',     flag: '🇵🇭' },
  { code: 'ta',    name: 'Tamil',       flag: '🇮🇳' },
  { code: 'te',    name: 'Telugu',      flag: '🇮🇳' },
  { code: 'th',    name: 'Thai',        flag: '🇹🇭' },
  { code: 'tr',    name: 'Turkish',     flag: '🇹🇷' },
  { code: 'uk',    name: 'Ukrainian',   flag: '🇺🇦' },
  { code: 'ur',    name: 'Urdu',        flag: '🇵🇰' },
  { code: 'vi',    name: 'Vietnamese',  flag: '🇻🇳' },
  { code: 'cy',    name: 'Welsh',       flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'yi',    name: 'Yiddish',     flag: '✡️' },
];

// Popular language pairs for quick chips
const POPULAR_TARGETS = [
  { code: 'fr', name: 'French',   flag: '🇫🇷' },
  { code: 'es', name: 'Spanish',  flag: '🇪🇸' },
  { code: 'de', name: 'German',   flag: '🇩🇪' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'ar', name: 'Arabic',   flag: '🇸🇦' },
  { code: 'zh', name: 'Chinese',  flag: '🇨🇳' },
  { code: 'ur', name: 'Urdu',     flag: '🇵🇰' },
  { code: 'hi', name: 'Hindi',    flag: '🇮🇳' },
  { code: 'ru', name: 'Russian',  flag: '🇷🇺' },
];
